# OVERRIDE #

languageCode = "en-us"
title = "AMKS"
baseURL = "https://www.amks.me"
copyright = "amk Â© 2020"

[params]
  # This will show the twitter icon which will link to twitter.com/your-twitter-handle
  # You can omit the @ symbol
  twitter = "amksomani"
  # This will show the github icon which will link to github.com/your-github-handle
  # You can omit the @ symbol
  github = "somaniarushi"
  sitename = "amks"
  description = "Serial tinkerer making the things that help other people make things. Student at UC Berkeley passionate about CS, Economics, and Entrepreneurship."


# OVERRIDE #

# DONT OVERRIDE #

[[menu.main]]
    identifier = "intro screen"
    name = "intro screen"
    title = "Home"
    url = "/"
    weight = "25"

[[menu.main]]
    identifier = "pause menu"
    name = "pause menu"
    title = "About"
    url = "https://dailyink.notion.site/pause-menu-a46c3370e4b94afeb922739b63a0e4f1?pvs=4"
    weight = "30"

preserveTaxonomyNames = true
disableToc = "false"

[taxonomies]
  tag = "tags"

# DONT OVERRIDE #

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false