# OVERRIDE #

languageCode = "en-us"
title = "AMKS"
baseURL = "https://www.amks.me"
copyright = "amk Â© 2020"

[params]
  # This will show the twitter icon which will link to twitter.com/your-twitter-handle
  # You can omit the @ symbol
  twitter = "amksomani"
  # This will show the github icon which will link to github.com/your-github-handle
  # You can omit the @ symbol
  github = "somaniarushi"
  sitename = "amks"
  description = "Serial tinkerer making the things that help other people make things. Student at UC Berkeley passionate about CS, Economics, and Entrepreneurship."


# OVERRIDE #

# DONT OVERRIDE #

[[menu.main]]
    identifier = "intro screen"
    name = "intro screen"
    title = "Home"
    url = "/"
    weight = "25"

[[menu.main]]
    identifier = "storyline"
    name = "storyline"
    title = "Storyline"
    url = "https://dailyink.notion.site/quest-log-6e5c31ee6c9747cc98db5fc73a007302"
    weight = "30"


[[menu.main]]
    identifier = "writings"
    name = "writings"
    title = "Writings"
    url = "https://dailyink.notion.site/Personal-Blog-e63f8119582841ca87acf13b70a51317"
    weight = "30"

[[menu.main]]
    identifier = "the daily ink"
    name = "the daily ink"
    title = "TDI"
    url = "https://dailyink.notion.site/the-daily-ink-d4c4144fd8c54779bf276b0e32d3622e"
    weight = "30"

[[menu.main]]
    identifier = "personal projects"
    name = "personal projects"
    title = "personal projects"
    url = "https://dailyink.notion.site/Research-Logs-e038beb1e36241d3aa52e608d682ff32"
    weight = "50"

preserveTaxonomyNames = true
disableToc = "false"

[taxonomies]
  tag = "tags"

# DONT OVERRIDE #

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false