# OVERRIDE #

languageCode = "en-us"
title = "AMKS"
baseURL = "https://www.amks.me"
copyright = "amk Â© 2020"

[params]
  # This will show the twitter icon which will link to twitter.com/your-twitter-handle
  # You can omit the @ symbol
  twitter = "amksomani"
  # This will show the github icon which will link to github.com/your-github-handle
  # You can omit the @ symbol
  github = "somaniarushi"
  sitename = "amks"
  description = "Making the things that help other people make things. Sophomore at UC Berkeley passionate about CS, Economics, Astrophysics and Entrepreneurship."


# OVERRIDE #

# DONT OVERRIDE #

[[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = "25"

[[menu.main]]
    identifier = "about"
    name = "about me"
    title = "About"
    url = "/about"
    weight = "30"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
  weight = "100"

[[menu.main]]
  identifier = "linkedin"
  name = "linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/arushisomani"
  weight = "50"

[[menu.main]]
  identifier = "projects"
  name = "projects"
  title = "Projects"
  url = "/projects"
  weight = "50"

[[menu.main]]
  identifier = "resume"
  name = "resume"
  title = "Resume"
  url = "/resume.pdf"
  weight = "50"

[[menu.main]]
  identifier = "newsletter"
  name = "newsletter"
  title = "Newsletter"
  url = "/newsletter"
  weight = "39"
  

preserveTaxonomyNames = true
disableToc = "false"

[taxonomies]
  tag = "tags"

# DONT OVERRIDE #

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false